[telemetry]
connection_string = "InstrumentationKey=bdc800b2-0c49-4ccd-9f8f-dbe2bfad0c09;IngestionEndpoint=https://westus2-2.in.applicationinsights.azure.com/;LiveEndpoint=https://westus2.livediagnostics.monitor.azure.com/;ApplicationId=50f68f9b-04c5-4162-aba6-afd462d8b153"
